### ISSUE TITLE
Language choosing

### ISSUE THREAD

**Issue by Hintsmth** [BluePointLilac/ContextMenuManager#50]
Ni hao!

How can I change language inside the program?

Thanks in advance!

**Comment by BluePointLilac** [comment]
![image](https://user-images.githubusercontent.com/55010935/114266209-a6562e80-9a27-11eb-8c40-4a3328dac130.png)
Please switch to the last option in the top toolbar of the program, and then switch to the second option in the left sidebar. When you see the second icon in the workspace, click it to jump to [GitHub](https://github.com/BluePointLilac/ContextMenuManager/tree/master/languages), where you can click the language you want, such as en- US.ini , and then copy the text to en- US.ini  Local files, click the first icon in the workspace to open the language folder and save it there. That's it. Then in the drop-down box of the workspace you will see what you want.
I'm sorry, because I'm an amateur programmer, limited technology, and the problem of Chinese firewall, I can't make the software perfect.
